### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by saeyama** [saeyama/nailier#1]
![entity-relationship-diagram](https://user-images.githubusercontent.com/64824195/174419623-bb6dcf11-7787-462c-808a-7afdb49d04c2.png)

**Comment by cafedomancer** [comment]
## 全般

* 参照するテーブルから参照されるテーブルへの関連 (Rails でいうところの belongs to) の多重度が 0..1 になっています。optional でないのであれば多重度は 1 になるはずなので見直してみてください。
* 上記と合わせて、多重度が 1 になる部分は外部キーにも NOT NULL 制約をかけておきましょう。
* `created_at`, `updated_at` はデフォルトで NOT NULL 制約がかかっているはずなので ER 図にもそれらを記載しておいてください。
* (`images`, `moves` については画面待ちなので別途コメントします)

## users

* `users.name` はアカウント名を格納するカラムですかね？ このアプリはアカウント名でログインできるようになっていたはずなので、`users.name` にも UNIQUE INDEX を張る必要があると思います。また name だと人の名前っぽい感じがするので、アカウント名であることが分かるような名前になっていたほうが良さそうです。
* `users.password-digest` だけ kebab-case になっています。Devise との絡みがあるので変更されるとは思いますが、snake_case に統一しておきましょう。

## designs

* `designs.kind` は "ハンド" や "フット" が入るカラムですかね？ であれば名前が一般的すぎるので、"ハンド" や "フット" が格納されることが分かるような具体的な名前をつける必要がありそうです。
* パーツやカラーが存在しないデザインもあるんでしょうか？ ないのであれば多重度は 1..* になると思うので必要に応じて修正してください。

## colors

* `colors.glitter` はラメあり・ラメなしを格納するカラムですかね？ 単純に lame とかのほうが読み替えるコストがなくて分かりやすい気がしました。また boolean のカラムに null が入っていると false との区別がつかないので NOT NULL 制約をかけておいたほうがよいです。
* `colors.name` にはどんな値が入りますか？ 画面には色の名前を入力するフィールドが見当たりませんでした。また色そのものの情報はどこに格納するんでしょうか？

## parts

* `parts.name` と `parts.size` は入力画面だと候補名が出てくるようになっていますが、このデータはどこに格納しておく (or どこから取ってくる) 予定ですか？
* `parts.number` は個数を格納するカラムですかね？ number だと意味している範囲が広くてわかりくいので quantity とかのほうが良いと思います。
* `parts.color` が varchar になっていますが、これには実際どんな値が入りますか？ というのと画面に出ている色の候補はどこにデータとして格納しておく予定ですか？
* このテーブルのカラムはいずれも NOT NULL 制約がかけられていませんが、ぜんぶ任意入力の項目なんでしょうか...？

## tags

* 名前のないタグは存在しないはずなので `tags.name` は NOT NULL 制約をかけておく必要があります。

## inquiries

* `inquiries.email` だけ string になっているのはなぜですか？

**Comment by saeyama** [comment]
@cafedomancer さん確認ありがとうございます。
DB設計を修正しました。
以下、ご指摘頂いた内容の修正及び回答です。
確認お願いします🙇‍♀️

## 全般
> 参照するテーブルから参照されるテーブルへの関連 (Rails でいうところの belongs to) の多重度が 0..1 になっています。optional でないのであれば多重度は 1 になるはずなので見直してみてください。
上記と合わせて、多重度が 1 になる部分は外部キーにも NOT NULL 制約をかけておきましょう。
created_at, updated_at はデフォルトで NOT NULL 制約がかかっているはずなので ER 図にもそれらを記載しておいてください。

修正しました🙇‍♀️

## users
> users.name はアカウント名を格納するカラムですかね？ このアプリはアカウント名でログインできるようになっていたはずなので、users.name にも UNIQUE INDEX を張る必要があると思います。また name だと人の名前っぽい感じがするので、アカウント名であることが分かるような名前になっていたほうが良さそうです。
users.password-digest だけ kebab-case になっています。Devise との絡みがあるので変更されるとは思いますが、snake_case に統一しておきましょう。

修正及びDeviseに伴うカラムを追加しました🙇‍♀️
あと、退会したかどうかがわかるwithdrawalカラムも追加しました。

## designs
> designs.kind は "ハンド" や "フット" が入るカラムですかね？ であれば名前が一般的すぎるので、"ハンド" や "フット" が格納されることが分かるような具体的な名前をつける必要がありそうです。
パーツやカラーが存在しないデザインもあるんでしょうか？ ないのであれば多重度は 1..* になると思うので必要に応じて修正してください。

修正しました🙇‍♀️
パーツ登録をしないケースも想定しているので、パーツは0..*にしてます。

## colors
> colors.glitter はラメあり・ラメなしを格納するカラムですかね？ 単純に lame とかのほうが読み替えるコストがなくて分かりやすい気がしました。また boolean のカラムに null が入っていると false との区別がつかないので NOT NULL 制約をかけておいたほうがよいです。

修正しました🙇‍♀️

> colors.name にはどんな値が入りますか？ 画面には色の名前を入力するフィールドが見当たりませんでした。また色そのものの情報はどこに格納するんでしょうか？

カラーピッカー及びカラーパレットで選定したHexとかRBGの値を想定しています。
上記指摘を受けて、ペーパープロトタイプを修正しました🙇‍♀️

## parts
> parts.name と parts.size は入力画面だと候補名が出てくるようになっていますが、このデータはどこに格納しておく (or どこから取ってくる) 予定ですか？

`active_hash` を使用する想定でおります。

> parts.number は個数を格納するカラムですかね？ number だと意味している範囲が広くてわかりくいので quantity とかのほうが良いと思います。

修正しました🙇‍♀️

> parts.color が varchar になっていますが、これには実際どんな値が入りますか？ というのと画面に出ている色の候補はどこにデータとして格納しておく予定ですか？

Hexのカラーを抜粋して`active_hash` を使用しようかと思ってました。

> このテーブルのカラムはいずれも NOT NULL 制約がかけられていませんが、ぜんぶ任意入力の項目なんでしょうか...？

登録されないことも想定しているので任意入力にしております。

## tags
> 名前のないタグは存在しないはずなので tags.name は NOT NULL 制約をかけておく必要があります。

修正しました🙇‍♀️

## inquiries
> inquiries.email だけ string になっているのはなぜですか？

修正漏れです🙇‍♀️直しました。

**Comment by saeyama** [comment]
@cafedomancer さん、後付けですいません。一点修正しました🙇‍♀️

## designs
> designs.kind は "ハンド" や "フット" が入るカラムですかね？ であれば名前が一般的すぎるので、"ハンド" や "フット" が格納されることが分かるような具体的な名前をつける必要がありそうです。
パーツやカラーが存在しないデザインもあるんでしょうか？ ないのであれば多重度は 1..* になると思うので必要に応じて修正してください。

> 修正しました🙇‍♀️
> パーツ登録をしないケースも想定しているので、パーツは0..*にしてます。

カラーも同様に登録をしないをケースもあると思ったのでで0..*に戻しました。

**Comment by cafedomancer** [comment]
## users

* `account` だと文字列ではなくレコードっぽい感じがするので `account_name` にしておいたほうがよいかもです。`account_name` にしておけば画面の項目名とも揃います 🙆 

> あと、退会したかどうかがわかるwithdrawalカラムも追加しました。

* ☝️ 物理削除ではなく論理削除にしている理由はなんですか？ `email` にユニークインデックスを張っているので、再登録されるケースを考えると厄介そうです。あと退会したのにデータが残っているのは、プライバシーポリシー的に問題がないのかどうかが気になります。

## designs

* `claw_part`: claw は動物のかぎ爪のことを指しているので別の単語のほうがよいかもです。いくつか案を考えてみたので参考にしてみてください 💁 `nail_part`, `body_part`, `hand_or_foot`, `part_type`

## colors

> カラーピッカー及びカラーパレットで選定したHexとかRBGの値を想定しています。
> 上記指摘を受けて、ペーパープロトタイプを修正しました🙇‍♀️

* 了解です。`parts` と合わせて 16 進数を保存しておくとよいですかね。保存する形式は整数 (`123456` だと `1193046` かな？) でも文字列 (`#123456`) でもどちらでも。ぱっと判断がつかなかったので都合のよいほうを選んで、ER 図もそれに合わせておいてください。
* ちなみに `name` という名前だと、上記のデータが入っていることが名前から推測できないので、別の名前を考える必要があります。
* 現在 `name` になっているものは必須の項目ですか？ それとも任意入力の項目ですか？ デザイン詳細の画面的に必須な気がするので、必須であれば NOT NULL 制約をかけておいてください。

## parts

> 登録されないことも想定しているので任意入力にしております。

* ぜんぶ任意入力だと謎のパーツが登録できちゃいませんかね...？ 詳細画面でパーツのデータとして表示できるものがなくなってしまう気がします。もう一度見直してみてください。

**Comment by saeyama** [comment]
@cafedomancer さん、確認ありがとうございます。
DB設計を修正しました。
確認お願いします🙇‍♀️

## users
> account だと文字列ではなくレコードっぽい感じがするので account_name にしておいたほうがよいかもです。account_name にしておけば画面の項目名とも揃います 🙆

修正しました🙇‍♀️

> あと、退会したかどうかがわかるwithdrawalカラムも追加しました。
☝️ 物理削除ではなく論理削除にしている理由はなんですか？ email にユニークインデックスを張っているので、再登録されるケースを考えると厄介そうです。あと退会したのにデータが残っているのは、プライバシーポリシー的に問題がないのかどうかが気になります。

そうですねっ…！
削除しました🙇‍♀️

## designs
> claw_part: claw は動物のかぎ爪のことを指しているので別の単語のほうがよいかもです。いくつか案を考えてみたので参考にしてみてください 💁 nail_part, body_part, hand_or_foot, part_type

ありがとうございます。
`nail_part`にしました！

一個気になったのが、`lame`なんですけど、ラメは和製英語で英単語だと違う意味になるようなのですが、、これは特に気にする必要はないのでしょうか…?

## colors
> カラーピッカー及びカラーパレットで選定したHexとかRBGの値を想定しています。
上記指摘を受けて、ペーパープロトタイプを修正しました🙇‍♀️

> 了解です。parts と合わせて 16 進数を保存しておくとよいですかね。保存する形式は整数 (123456 だと 1193046 かな？) でも文字列 (#123456) でもどちらでも。ぱっと判断がつかなかったので都合のよいほうを選んで、ER 図もそれに合わせておいてください。
ちなみに name という名前だと、上記のデータが入っていることが名前から推測できないので、別の名前を考える必要があります。

`hex_number`にしました🙇‍♀️

> 現在 name になっているものは必須の項目ですか？ それとも任意入力の項目ですか？ デザイン詳細の画面的に必須な気がするので、必須であれば NOT NULL 制約をかけておいてください。

`NOT NULL`追加しました。

## parts
> 登録されないことも想定しているので任意入力にしております。

> ぜんぶ任意入力だと謎のパーツが登録できちゃいませんかね...？ 詳細画面でパーツのデータとして表示できるものがなくなってしまう気がします。もう一度見直してみてください。

自分の認識度が足りず、`NOT NULL`不要にしてましたが、`hex_number`と`quantity`に登録がなかった場合のデフォルト値を設定します。(Colorsの`hex_number`とVideosの`url`も)

**Comment by saeyama** [comment]
@cafedomancer さん、確認ありがとうございます。
URI設計を修正しました。
確認お願いします🙇‍♀️

## 全般
> リダイレクト先は列を追加して以下のように書いておいてもらってもよいですか？ GET のところは空欄でよいです。リダイレクト先のルーティングの行自体はルーティングの一覧として必要なので、整理して残しておいてください。

修正しました🙇‍♀️

 ## ユーザー
> ユーザー登録後は /users/registration にリダイレクトするのではなくフラッシュメッセージ付きでトップページにリダイレクトすればよい気がしました。
ユーザー削除後も /users/withdrawal にリダイレクトするのではなくフラッシュメッセージ付きでトップページにリダイレクトすればよい気がしました。
GET /users/:id ユーザー情報更新後のリダイレクトページの表示
☝️ ここ、まだ user の id が含まれています。PATCH /users/:id と同じ問題があるので修正が必要です。

修正しました🙇‍♀️

## パスワード再設定
> パスワード再設定のメール登録後のページの表示
☝️ これっていつ表示される画面ですか？ というかメールを送信するとき POST リクエストを発行しなきゃいけない気がするのですが、それを受けるルーティングがそもそもないような気がしました。

POSTリクエスト追記しました🙇‍♀️
メールを送信したらフラッシュメッセージでお知らせして、パスワード再設定のメール送信ページにリダイレクトさせるようにします。

> パスワード更新後のリダイレクトページの表示
☝️ パスワードの更新後はログインページにリダイレクトすればよいと思います。

修正しました🙇‍♀️

**Comment by cafedomancer** [comment]
> 一個気になったのが、lameなんですけど、ラメは和製英語で英単語だと違う意味になるようなのですが、、これは特に気にする必要はないのでしょうか…?

たぶん元はフランス語なので大丈夫かなーというのと、カラム名を英語にすると `glitter (英語) <-> ラメ (日本語)` の読み替えが大変かなと思ったので `lame` を採用しました。読み替えが大変でなければ `glitter` にしても OK です 🙆 https://ja.wikipedia.org/wiki/%E3%83%A9%E3%83%A1

> 自分の認識度が足りず、NOT NULL不要にしてましたが、hex_numberとquantityに登録がなかった場合のデフォルト値を設定します。(Colorsのhex_numberとVideosのurlも)

あ、デフォルト値があるんですね。であれば ER 図にデフォルト値も記載しておいてください。

**Comment by saeyama** [comment]
@cafedomancer さん確認ありがとうございます。
DB設計を修正しました。
確認お願いします🙇‍♀️

> たぶん元はフランス語なので大丈夫かなーというのと、カラム名を英語にすると glitter (英語) <-> ラメ (日本語) の読み替えが大変かなと思ったので lame を採用しました。読み替えが大変でなければ glitter にしても OK です 🙆 https://ja.wikipedia.org/wiki/%E3%83%A9%E3%83%A1

ありがとうございます🙇‍♀️今後のレビューのことも踏まえ、`lame`のままにします！

> 自分の認識度が足りず、NOT NULL不要にしてましたが、hex_numberとquantityに登録がなかった場合のデフォルト値を設定します。(Colorsのhex_numberとVideosのurlも)
あ、デフォルト値があるんですね。であれば ER 図にデフォルト値も記載しておいてください。

設定しました。文字が小さいので、下記に記述します。

**Colors/Parts**
hex_number `DEFAULT 'unselected'`

**Colors**
lame `DEFAULT false`

**Parts**
quantity `DEFAULT 0`

**Videos**
url `DEFAULT 'unregistered'`

**Comment by cafedomancer** [comment]
> **Colors/Parts** hex_number `DEFAULT 'unselected'`

`'unselected'` という値は NULL と変わりがないので、これをデフォルト値として設定するくらいなら、NULL を許可して任意入力にしておいたほうがよさそうです 😵 

> **Colors** lame `DEFAULT false`

これは OK です 🙆 

> **Parts** quantity `DEFAULT 0`

これも個数 0 のパーツって、登録する意味がないような気がするので、NOT NULL にしつつ必須入力にするか、NULL を許可して任意入力にしておいたほうがよさそうです。ちなみにパーツの情報でいちばん重要なものって、パーツ名・大きさ・個数・カラーのうちどれですか？ そこだけ NOT NULL にして必須入力にするのがいいんじゃないかなと思いました。

> **Videos** url `DEFAULT 'unregistered'`

これも URL が登録されていない動画は、そもそも登録される意味がないような気がするので、NOT NULL にしつつ必須入力しておいたほうがよいと思います。

**Comment by saeyama** [comment]
@cafedomancer さん、修正をする前に、hex_numberについてと質問があります🙏

`hex_number`は今一度調べなおして、色(16進数)+不透明度をセットとして登録したいと思っているので`無色`をデフォルト値にしたいと思います。
最初どぉ登録していいか定まってなくて`'unselected'`にしてました…。

- 16進数(なんの色でもいいけど黒#000000)＋00(不透明度0%)
`DEFAULT '#00000000’` にしようと思います。

[透明度（アルファ）を16進数（HEX）のカラーコードに置換](https://qiita.com/CUTBOSS/items/a96fb369e5d1d8eda0da)
↑ちょっとスクロールすると一覧があります。
[NPM でインストール可能なカラーピッカー](https://r17n.page/2020/09/09/npm-color-picker-libraries/)
[@simonwep/pickr \- npm](https://www.npmjs.com/package/@simonwep/pickr)

クリアを一つの色としてColorsに登録するケースもあるということに気づいたので、それは別の番号(#FFFFFF00　※#FFFFFFは白)として、カラーパレットに設置するか、もしくは、別で切り出して表示をして選択できるようにしたいと思います。

> これも個数 0 のパーツって、登録する意味がないような気がするので、NOT NULL にしつつ必須入力にするか、NULL を許可して任意入力にしておいたほうがよさそうです。ちなみにパーツの情報でいちばん重要なものって、パーツ名・大きさ・個数・カラーのうちどれですか？ そこだけ NOT NULL にして必須入力にするのがいいんじゃないかなと思いました。

Partsは登録するなら全部必要だし、登録しないなら全部不要になるので…Partsも`hex_number`をDEFAULT値とすれば良いのかなと思ったのですが、ただ全ての項目について、全部登録されないケースもあると想定していたので、その上でデフォルト設定しておけば良いのかなという認識でいました。

Designsにそれぞれの項目(画像・動画・パーツ・カラー)を登録するかどうかをBOOLEANで設定して、trueだったら登録するような設計でも良いのでしょうか。

**Comment by cafedomancer** [comment]
ちょっと確認したいのですがデフォルト値を設定したいのはどうしてでしたっけ？ 情報が入力されていないテーブルのデータは別に保存しなければいいんじゃないかと思うのですが...。designs テーブルから各テーブルの多重度は 0 を許容するようになっていますし。

> Designsにそれぞれの項目(画像・動画・パーツ・カラー)を登録するかどうかをBOOLEANで設定して、trueだったら登録するような設計でも良いのでしょうか。

画面のデザインとしてはアリだと思います。ただチェックの情報はデータベースに保存しても何にもならないので保存しなくてよいです。

**Comment by saeyama** [comment]
@cafedomancer さん、確認ありがとうございます🙇‍♀️
…根本勘違いをしてて、デザイン登録したら、多のところもレコード作られる前提で進めてました。
調べて修正し直しました。確認お願いします🙏

**Comment by cafedomancer** [comment]
確認しました！ OK です 👌 

> …根本勘違いをしてて、デザイン登録したら、多のところもレコード作られる前提で進めてました。

あ、なるほど、やはり。そうすると、もしかしたら `colors.lame` のデフォルト値も外せるかもしれないので、必要があれば外しておいてください。画面だとデフォルトが「なし」になっているので、付けておいてもいい気もします。

**Comment by saeyama** [comment]
@cafedomancer さん、確認ありがとうございました🙇‍♀️

> あ、なるほど、やはり。そうすると、もしかしたら colors.lame のデフォルト値も外せるかもしれないので、必要があれば外しておいてください。画面だとデフォルトが「なし」になっているので、付けておいてもいい気もします。

…🙏
colors.lame のデフォルト値は外しました！
