### ISSUE TITLE
URI設計

### ISSUE THREAD

**Issue by saeyama** [saeyama/nailier#2]
### root

| Method| Path   | Description | 
|--------|-------|----------|
| GET    | / | トップページの表示 |

### ユーザー

| Method| Path   | Description | Redirect |
|--------|-------|----------|-----------|
| GET    | /users/new| ユーザー情報の登録ページの表示| 
| POST   | /users | ユーザー情報の登録 |/|
| GET    | /users/edit   | ユーザー情報の編集      |
| PATCH   | /users        | ユーザー情報の更新     |/users|
| DELETE | /users | ユーザー情報の削除   |/|
| GET  | /users  | ユーザー情報の詳細     ||

### ログイン・ログアウト

| Method| Path   | Description | Redirect |
|--------|-------|----------|-----------|
| GET    | /users/sign_in      | ログインページの表示  |
| POST   | /users/sign_in     | ログインの処理 |/designs |
| DELETE  | /users/sign_out      | ログアウトの処理   |/|

### パスワード再設定

| Method| Path   | Description | Redirect |
|--------|-------|----------|-----------|
| GET | /users/password/new  | パスワード再設定のメール送信ページの表示   |
| POST |/users/password | パスワード再設定のメールを送信 | /users/password/new  | 
| GET | /users/password/edit | パスワード再設定のページの表示 |
| PATCH | /users/password | パスワードの更新 | /users/sign_in  |

### デザイン

| Method| Path   | Description | Redirect |
|--------|-------|----------|-----------|
| GET    | /designs                     | デザイン情報の一覧    |
| GET    | /designs/new           | デザイン情報の登録ページの表示  |
| POST   | /designs      | デザイン情報の登録完了  |/designs/:id|
| GET    | /designs/:id/edit | デザイン情報の編集ページの表示   |
| PATCH   | /designs/:id      | デザイン情報を更新 |/designs/:id|
| DELETE   | /designs/:id       | デザイン情報の削除    |/designs|
| GET   | /designs/:id       | デザイン情報の詳細    |

### 問い合わせ

| Method| Path   | Description | Redirect |
|--------|-------|----------|-----------|
| GET    | /inquiries/new     | 問い合わせの作成ページの表示  |
| POST   | /inquiries             | 問い合わせ内容の登録完了 |/inquiries/thanks |
| GET  |  /inquiries/thanks | 問い合わせ登録完了後 |

**Comment by cafedomancer** [comment]
## 全般

* `GET` のルーティングは基本的にページを表示を行うルーティングなので description にも「〜ページの表示」のように書いておいてください。`GET` 以外のルーティングについては「〜の登録・更新・削除」または「〜の登録処理・更新処理・削除処理」のように書いておいてください。
* `GET` 以外のルーティングについてはリダイレクト先なども書いておくと、実装の段になって困ることがなくなるかなと思いました。

## ユーザー

* `GET /users/:edit` で `:edit` が segment になっていますが、ここには何が入るんでしょうか？
* `PATCH /users/:id` で 更新処理を受けるのはセキュリティ的にまずそうです。`:id` が予測可能なものであれば `PATCH /users/123` のようなリクエストを発行して任意のユーザーの情報を更新できてしまいます。現在のユーザーのみ更新できればよいはずなので `:id` はいらないはずです。ルーティングを見直してみてください。
* ユーザー情報の削除は `DELETE /users` か `DELETE /user` でいいんじゃないかなと思いました。retirement は退会を意味する言葉としてはあまり一般的ではない気がします。

## ログイン・ログアウト

* ログアウトは `POST /logout` でいいんじゃないでしょうか。logout を DELETE するだと意味的によく分からない気がします。リソースの操作として表現したいのであればログインは `POST /sessions`、ログアウトは `DELETE /sessions` のようにするとよいと思います。session のような singular resource でもよいです。

## デザイン

* Rails のアクションの標準的な順番 (index, new/create, edit/update, destroy) に対応させておいたほうが分かりやすいと思うので "ネイルデザイン一覧" は先頭に書いておいてください。
* segment は `:design_id` ではなく `:id` にしておきましょう。

## 問い合わせ

* ここだけ singular resource になっているのは意図してそうしているものですか？ singular resource になっていること自体は OK なので単純に確認です。
* ちなみに問い合わせが完了したときはどのページが表示されますか？ (or どのページに遷移しますか？)

**Comment by saeyama** [comment]
@cafedomancer さん確認ありがとうございます。
URI設計を修正しました。
以下、ご指摘頂いた内容の修正及び回答です。
確認お願いします🙇‍♀️

## 全般
> GET のルーティングは基本的にページを表示を行うルーティングなので description にも「〜ページの表示」のように書いておいてください。GET 以外のルーティングについては「〜の登録・更新・削除」または「〜の登録処理・更新処理・削除処理」のように書いておいてください。
GET 以外のルーティングについてはリダイレクト先なども書いておくと、実装の段になって困ることがなくなるかなと思いました。

修正及びリダイレクト先も追加しました🙇‍♀️

## ユーザー
> GET /users/:edit で :edit が segment になっていますが、ここには何が入るんでしょうか？

入力誤りです🙏 修正しました🙇‍♀️

> #PATCH /users/:id で 更新処理を受けるのはセキュリティ的にまずそうです。:id が予測可能なものであれば PATCH /users/123 のようなリクエストを発行して任意のユーザーの情報を更新できてしまいます。現在のユーザーのみ更新できればよいはずなので :id はいらないはずです。ルーティングを見直してみてください。

> ユーザー情報の削除は DELETE /users か DELETE /user でいいんじゃないかなと思いました。retirement は退会を意味する言葉としてはあまり一般的ではない気がします。

修正しました🙇‍♀️

## ログイン・ログアウト
> ログアウトは POST /logout でいいんじゃないでしょうか。logout を DELETE するだと意味的によく分からない気がします。リソースの操作として表現したいのであればログインは POST /sessions、ログアウトは DELETE /sessions のようにするとよいと思います。session のような singular resource でもよいです。

他の方のとDeviseが実装されているアプリを参考に、全体的に修正し直しました🙇‍♀️

## デザイン
> Rails のアクションの標準的な順番 (index, new/create, edit/update, destroy) に対応させておいたほうが分かりやすいと思うので "ネイルデザイン一覧" は先頭に書いておいてください。
segment は :design_id ではなく :id にしておきましょう。

修正しました🙇‍♀️

## 問い合わせ
> ここだけ singular resource になっているのは意図してそうしているものですか？ singular resource になっていること自体は OK なので単純に確認です。

複数系に修正しました🙇‍♀️

> ちなみに問い合わせが完了したときはどのページが表示されますか？ (or どのページに遷移しますか？)

リダイレクトページを追加しました🙇‍♀️

**Comment by cafedomancer** [comment]
おっ、だいぶいい感じです 🙆 

## 全般

* リダイレクト先は列を追加して以下のように書いておいてもらってもよいですか？ `GET` のところは空欄でよいです。リダイレクト先のルーティングの行自体はルーティングの一覧として必要なので、整理して残しておいてください。

| Method | Path | Description | <リダイレクト先を表す見出し> |
| -- | -- | -- | -- |
| POST | /users | ユーザー情報の登録 | <パスか画面名のどちらか> |
| GET | <リダイレクト先> | <画面名> |  |

## ユーザー

* ユーザー登録後は `/users/registration` にリダイレクトするのではなくフラッシュメッセージ付きでトップページにリダイレクトすればよい気がしました。
* ユーザー削除後も `/users/withdrawal` にリダイレクトするのではなくフラッシュメッセージ付きでトップページにリダイレクトすればよい気がしました。

> GET /users/:id ユーザー情報更新後のリダイレクトページの表示

* ☝️ ここ、まだ user の id が含まれています。`PATCH /users/:id` と同じ問題があるので修正が必要です。

## パスワード再設定

> パスワード再設定のメール登録後のページの表示

* ☝️ これっていつ表示される画面ですか？ というかメールを送信するとき POST リクエストを発行しなきゃいけない気がするのですが、それを受けるルーティングがそもそもないような気がしました。

> パスワード更新後のリダイレクトページの表示

* ☝️ パスワードの更新後はログインページにリダイレクトすればよいと思います。

## 問い合わせ

* `Inquiries` の先頭の `I` が大文字になっていそうです。

**Comment by saeyama** [comment]
@cafedomancer さん、大変失礼しました。
URI設計のコメント先を誤ってました。
誤ってコメントした箇所は削除しました。
申し訳ありません💦

改めて、確認お願いします🙇‍♀️

## 全般
> リダイレクト先は列を追加して以下のように書いておいてもらってもよいですか？ GET のところは空欄でよいです。リダイレクト先のルーティングの行自体はルーティングの一覧として必要なので、整理して残しておいてください。

修正しました🙇‍♀️

 ## ユーザー
> ユーザー登録後は /users/registration にリダイレクトするのではなくフラッシュメッセージ付きでトップページにリダイレクトすればよい気がしました。
ユーザー削除後も /users/withdrawal にリダイレクトするのではなくフラッシュメッセージ付きでトップページにリダイレクトすればよい気がしました。
GET /users/:id ユーザー情報更新後のリダイレクトページの表示
☝️ ここ、まだ user の id が含まれています。PATCH /users/:id と同じ問題があるので修正が必要です。

修正しました🙇‍♀️

## パスワード再設定
> パスワード再設定のメール登録後のページの表示
☝️ これっていつ表示される画面ですか？ というかメールを送信するとき POST リクエストを発行しなきゃいけない気がするのですが、それを受けるルーティングがそもそもないような気がしました。

POSTリクエスト追記しました🙇‍♀️
メールを送信したらフラッシュメッセージでお知らせして、パスワード再設定のメール送信ページにリダイレクトさせるようにします。

> パスワード更新後のリダイレクトページの表示
☝️ パスワードの更新後はログインページにリダイレクトすればよいと思います。

修正しました🙇‍♀️

**Comment by cafedomancer** [comment]
* リダイレクト先のルーティングはどこか 1 箇所だけに書いてあればそれで OK です 🙆 たとえばトップページのルーティングを root 以外に重複して書く必要はないです。

> PUT  /users/password パスワードの更新 /users/sign_in

* ☝️ ここだけ PATCH ではなく PUT になっていました。どちらでもよいですがどちらかに統一しておいてください。

**Comment by saeyama** [comment]
@cafedomancer さん確認ありがとうございます。
URI設計を修正しました。
確認お願いします🙇‍♀️

> リダイレクト先は列を追加して以下のように書いておいてもらってもよいですか？ GET のところは空欄でよいです。リダイレクト先のルーティングの行自体はルーティングの一覧として必要なので、整理して残しておいてください。

> リダイレクト先のルーティングはどこか 1 箇所だけに書いてあればそれで OK です 🙆 たとえばトップページのルーティングを root 以外に重複して書く必要はないです。

上記踏まえ、修正しました🙇‍♀️

> PUT /users/password パスワードの更新 /users/sign_in
☝️ ここだけ PATCH ではなく PUT になっていました。どちらでもよいですがどちらかに統一しておいてください。

いくつか参考にさせて頂いた内容がPUTになってたので、そうしてました。
[参考サイト](https://qiita.com/murata0705/items/52538c08778c39a91ec2)のように、
- PUTは更新というよりは置換
- PATCHは既存のリソースを更新・変更・修正

という認識でいたので、PATCHにしました。

**Comment by cafedomancer** [comment]
赤枠の GET が消えてしまっているようでした...？ GET を追加しておいてください 🙏 

<img width="610" alt="Screen Shot 2022-06-16 at 21 36 08" src="https://user-images.githubusercontent.com/7645585/174071131-951e953c-6f9a-4822-962e-aff18c69b637.png">
<img width="627" alt="Screen Shot 2022-06-16 at 21 47 10" src="https://user-images.githubusercontent.com/7645585/174072928-eac188a5-ddb8-4531-86de-6533f6ebcff6.png">
<img width="706" alt="Screen Shot 2022-06-16 at 21 36 11" src="https://user-images.githubusercontent.com/7645585/174071116-68c873bd-efc4-4b62-8ef0-fb321bdb87ec.png">

**Comment by saeyama** [comment]
@cafedomancer さん、意図が最後まで汲み取れてなかったです。
`GET`を追記しました🙏
